name: Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        # All commands should be platform agnostic
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install modules
              run: npm i

            - name: Build
              run: npm run build
